### ISSUE TITLE
Some thoughts for improvements

### ISSUE THREAD

**Issue by martbhell** [mhakala/ansible-role-lustre_client#6]
Hello :)

a) Any reason why you are using shell and not command?
b) It would also be possible to check the return code of the command with something like "test_grep.rc != 0 "

c) From how I understand this change - it only makes a change if the stdout is not empty - so if the grep finds lustre in fstab. Doesn't this mean it won't add it if it doesn't find anything?

d) See "systemctl status *.mount". On changing, perhaps it would also be good to run a "systemctl daemon-reload" with a handler?

**Comment by mhakala** [comment]
Thanks for the comments. I did tune things a bit. For a), b) and c) the easier optios was actually fix the regex line that was causing issues in the first place. For d) I assume best option would be to migrate to ansible mount module. Have to do some testing in some point.

**Comment by martbhell** [comment]
Looks like this is using the mount module now, closing :)
